# Generated by Django 4.1.2 on 2022-10-19 13:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('body', models.TextField(blank=True, max_length=4096, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/journal')),
                ('deleted', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
